apiVersion: apps/v1
kind: Deployment
metadata:
  name: breast-cancer
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      bc: web
  template:
    metadata:
      labels:
        bc: web
    spec:
      containers:
      - name: bb-site
        image: saptarshidatta96/breast_cancer:latest
---
apiVersion: v1
kind: Service
metadata:
  name: breast-cancer-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bc: web
  ports:
  - port: 12345
    targetPort: 12345
    nodePort: 30001

  type: LoadBalancer
  selector:
    bc: web
  ports:
  - port: 12345
    targetPort: 12345